version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  ApplicationStop:
    - location: deployment_scripts/stop_server.sh
      timeout: 300
      runas: root
      
  BeforeInstall:
    - location: deployment_scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: deployment_scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deployment_scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: deployment_scripts/validate_service.sh
      timeout: 300
      runas: root
  
